;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-rectangle
        markdown-enter-key
        markdown-exdent-or-delete
        open-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        ))
